export const USER_INFO = 'USER_INFO'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_SESSION = 'USER_SESSION'
export const USER_CODE = 'USER_CODE'
export const USER_MOBILE_LOGIN = 'USER_MOBILE_LOGIN'
